// Audia — Guided session, category and state definitions

const CATEGORIES = [
  {
    id: 'sleep',
    name: 'Sono Profundo',
    description: 'Protocolos Delta para desacelerar e dormir',
    icon: '🌙',
    gradient: 'linear-gradient(135deg, #10101a, #20203a)',
    freqRange: 'Delta · 0.5Hz - 4Hz',
  },
  {
    id: 'relax',
    name: 'Ansiedade & Calma',
    description: 'Theta, Alpha e sons naturais para regular o corpo',
    icon: '🌊',
    gradient: 'linear-gradient(135deg, #0f1f1a, #1f3a30)',
    freqRange: 'Theta · 4Hz - 8Hz',
  },
  {
    id: 'focus',
    name: 'Foco Profundo',
    description: 'Alpha e Beta suave para entrar em modo de execução',
    icon: '🎯',
    gradient: 'linear-gradient(135deg, #1f1d12, #3a341e)',
    freqRange: 'Alpha · 8Hz - 14Hz',
  },
  {
    id: 'clarity',
    name: 'Reset Mental',
    description: 'Protocolos curtos para limpar excesso de pensamentos',
    icon: '✨',
    gradient: 'linear-gradient(135deg, #171722, #2b2b38)',
    freqRange: 'Alpha + Theta',
  },
  {
    id: 'energy',
    name: 'Energia Imediata',
    description: 'Beta controlado para ativacao sem cafeina',
    icon: '⚡',
    gradient: 'linear-gradient(135deg, #24180f, #4a2c18)',
    freqRange: 'Beta · 14Hz - 30Hz',
  },
  {
    id: 'meditation',
    name: 'Meditação',
    description: 'Theta profundo e sons sagrados para silêncio interior',
    icon: '🕉️',
    gradient: 'linear-gradient(135deg, #12102a, #241e4a)',
    freqRange: 'Theta · 4Hz - 6Hz · 528Hz',
  },
  {
    id: 'creative',
    name: 'Criatividade',
    description: 'Alpha flow para destravar ideias e inspiração',
    icon: '🎨',
    gradient: 'linear-gradient(135deg, #0e1f1e, #1a3a38)',
    freqRange: 'Alpha · 10Hz · 432Hz',
  },
  {
    id: 'performance',
    name: 'Alta Performance',
    description: 'Beta alto para esforço máximo físico ou mental',
    icon: '🏆',
    gradient: 'linear-gradient(135deg, #1f0e0e, #3a1a1a)',
    freqRange: 'Beta · 20Hz - 30Hz · 40Hz',
  },
];

const MENTAL_STATES = [
  {
    id: 'ansioso',
    label: 'Ansioso',
    icon: '🫁',
    description: 'Respiracao curta, tensao ou urgencia interna.',
    idealSession: 'anxiety-now',
    idealFrequency: 'Theta 6Hz + 432Hz',
    idealDuration: 5,
    metric: 'anxiety',
    intent: 'baixar a ativacao do corpo agora',
  },
  {
    id: 'cansado',
    label: 'Cansado',
    icon: '🌙',
    description: 'Corpo pesado, mente lenta ou vontade de deitar.',
    idealSession: 'sleep-15',
    idealFrequency: 'Delta 2Hz + chuva',
    idealDuration: 15,
    metric: 'sleep',
    intent: 'guiar o corpo para repouso rápido',
  },
  {
    id: 'distraido',
    label: 'Distraído',
    icon: '🎯',
    description: 'Dificuldade de começar ou manter atenção.',
    idealSession: 'focus-5',
    idealFrequency: 'Alpha 10Hz + Beta 14Hz',
    idealDuration: 5,
    metric: 'focus',
    intent: 'entrar em foco profundo com pouco atrito',
  },
  {
    id: 'sem-energia',
    label: 'Sem energia',
    icon: '⚡',
    description: 'Baixa motivacao, sonolencia ou inicio lento.',
    idealSession: 'energy-now',
    idealFrequency: 'Beta 20Hz',
    idealDuration: 3,
    metric: 'energy',
    intent: 'ativar sem excesso de estímulo',
  },
  {
    id: 'pensando-demais',
    label: 'Pensando demais',
    icon: '✨',
    description: 'Muitos pensamentos, ruminação ou mente acelerada.',
    idealSession: 'mental-reset-3',
    idealFrequency: 'Theta 7Hz + ruído rosa',
    idealDuration: 3,
    metric: 'clarity',
    intent: 'criar silencio mental em poucos minutos',
  },
];

const OUTCOME_METRICS = {
  anxiety: {
    label: 'Ansiedade',
    beforeLabel: 'Nivel antes',
    afterLabel: 'Nivel depois',
    unit: '/5',
    lowerIsBetter: true,
  },
  sleep: {
    label: 'Tempo até relaxar',
    beforeLabel: 'Agitacao antes',
    afterLabel: 'Relaxamento depois',
    unit: '/5',
    lowerIsBetter: true,
  },
  focus: {
    label: 'Foco',
    beforeLabel: 'Distração antes',
    afterLabel: 'Clareza depois',
    unit: '/5',
    lowerIsBetter: true,
  },
  energy: {
    label: 'Energia',
    beforeLabel: 'Baixa energia antes',
    afterLabel: 'Ativacao depois',
    unit: '/5',
    lowerIsBetter: true,
  },
  clarity: {
    label: 'Carga mental',
    beforeLabel: 'Ruido mental antes',
    afterLabel: 'Ruido mental depois',
    unit: '/5',
    lowerIsBetter: true,
  },
  meditation: {
    label: 'Presença',
    beforeLabel: 'Agitação antes',
    afterLabel: 'Silêncio depois',
    unit: '/5',
    lowerIsBetter: true,
  },
  creative: {
    label: 'Criatividade',
    beforeLabel: 'Bloqueio antes',
    afterLabel: 'Flow depois',
    unit: '/5',
    lowerIsBetter: false,
  },
  performance: {
    label: 'Performance',
    beforeLabel: 'Prontidão antes',
    afterLabel: 'Pico depois',
    unit: '/5',
    lowerIsBetter: false,
  },
};

const SESSIONS = [
  {
    id: 'sleep-15',
    category: 'sleep',
    name: 'Dormir em 15 minutos',
    objective: 'Desacelerar o corpo e preparar sono profundo.',
    description: 'Delta 2Hz com chuva contínua para reduzir alerta e facilitar o sono.',
    duration: 15,
    icon: '🌙',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Delta 2Hz',
    soundLabel: 'Chuva',
    metric: 'sleep',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 180, beat: 2 },
      ambient: 'rain',
      ambientGain: 0.26,
      noise: 'brown',
      noiseGain: 0.16,
      binauralGain: 0.14,
    },
    tags: ['sono', 'delta', 'chuva', '15 min'],
    stateTags: ['cansado'],
    moodTags: ['cansado', 'dormir'],
  },
  {
    id: 'focus-5',
    category: 'focus',
    name: 'Foco profundo em 5 minutos',
    objective: 'Sair da distração e começar uma tarefa.',
    description: 'Alpha 10Hz com Beta suave para foco calmo e rápido.',
    duration: 5,
    icon: '🎯',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Alpha 10Hz + Beta 14Hz',
    soundLabel: 'Ruido rosa',
    metric: 'focus',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 220, beat: 10 },
      secondaryBinaural: { base: 260, beat: 14 },
      noise: 'pink',
      noiseGain: 0.09,
      binauralGain: 0.18,
      secondaryGain: 0.08,
    },
    tags: ['foco', 'alpha', 'beta', '5 min'],
    stateTags: ['distraido'],
    moodTags: ['distraido', 'focar'],
  },
  {
    id: 'anxiety-now',
    category: 'relax',
    name: 'Reduzir ansiedade agora',
    objective: 'Diminuir urgência interna e tensão corporal.',
    description: 'Theta 6Hz, 432Hz e mar contínuo para regular a respiração.',
    duration: 5,
    icon: '🫁',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Theta 6Hz + 432Hz',
    soundLabel: 'Mar',
    metric: 'anxiety',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 200, beat: 6 },
      tone: 432,
      toneGain: 0.07,
      ambient: 'ocean',
      ambientGain: 0.2,
      noise: 'pink',
      noiseGain: 0.08,
      binauralGain: 0.13,
    },
    tags: ['ansiedade', 'theta', '432hz', '5 min'],
    stateTags: ['ansioso'],
    moodTags: ['ansioso', 'ansiedade', 'calmar'],
  },
  {
    id: 'mental-reset-3',
    category: 'clarity',
    name: 'Reset mental em 3 minutos',
    objective: 'Interromper ruminação e recuperar controle.',
    description: 'Theta 7Hz com ruído rosa para baixar a velocidade dos pensamentos.',
    duration: 3,
    icon: '✨',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Theta 7Hz',
    soundLabel: 'Ruido rosa',
    metric: 'clarity',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 210, beat: 7 },
      noise: 'pink',
      noiseGain: 0.12,
      binauralGain: 0.16,
    },
    tags: ['reset', 'theta', '3 min'],
    stateTags: ['pensando-demais', 'ansioso'],
    moodTags: ['pensando-demais', 'calmar'],
  },
  {
    id: 'energy-now',
    category: 'energy',
    name: 'Energia imediata',
    objective: 'Ativar corpo e mente sem perder controle.',
    description: 'Beta 20Hz com textura clara para iniciar o dia ou retomar o ritmo.',
    duration: 3,
    icon: '⚡',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Beta 20Hz',
    soundLabel: 'Ruido branco leve',
    metric: 'energy',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 220, beat: 20 },
      noise: 'white',
      noiseGain: 0.07,
      binauralGain: 0.18,
    },
    tags: ['energia', 'beta', '3 min'],
    stateTags: ['sem-energia', 'cansado'],
    moodTags: ['sem-energia', 'energia'],
  },
  {
    id: 'calm-10',
    category: 'relax',
    name: 'Calma estável em 10 minutos',
    objective: 'Sustentar relaxamento depois de um pico de tensão.',
    description: 'Alpha 8Hz com floresta para regular o sistema nervoso.',
    duration: 10,
    icon: '🌿',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Alpha 8Hz',
    soundLabel: 'Floresta',
    metric: 'anxiety',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 200, beat: 8 },
      ambient: 'forest',
      ambientGain: 0.18,
      noise: 'brown',
      noiseGain: 0.1,
      binauralGain: 0.14,
    },
    tags: ['calma', 'alpha', 'floresta', '10 min'],
    stateTags: ['ansioso', 'pensando-demais'],
    moodTags: ['ansioso', 'calmar'],
  },
  {
    id: 'micro-nap-10',
    category: 'sleep',
    name: 'Descanso profundo em 10 minutos',
    objective: 'Baixar fadiga sem entrar em uma sessão longa.',
    description: 'Delta leve com ruído marrom para repouso curto.',
    duration: 10,
    icon: '💤',
    featured: false,
    guided: true,
    premium: false,
    frequencyLabel: 'Delta 3Hz',
    soundLabel: 'Ruido marrom',
    metric: 'sleep',
    expectedImpact: 1,
    audioConfig: {
      binaural: { base: 170, beat: 3 },
      noise: 'brown',
      noiseGain: 0.22,
      binauralGain: 0.12,
    },
    tags: ['descanso', 'delta', '10 min'],
    stateTags: ['cansado'],
    moodTags: ['cansado', 'dormir'],
  },
  {
    id: 'performance-10',
    category: 'focus',
    name: 'Alta performance em 10 minutos',
    objective: 'Preparar uma janela de trabalho intenso.',
    description: 'Alpha, Beta e 40Hz em camadas para foco sustentado.',
    duration: 10,
    icon: '🚀',
    featured: false,
    guided: true,
    premium: true,
    frequencyLabel: 'Alpha + Beta + 40Hz',
    soundLabel: 'Ruido rosa',
    metric: 'focus',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 200, beat: 12 },
      secondaryBinaural: { base: 240, beat: 20 },
      tone: 40,
      toneGain: 0.03,
      noise: 'pink',
      noiseGain: 0.08,
      binauralGain: 0.16,
      secondaryGain: 0.08,
    },
    tags: ['premium', 'foco', 'performance'],
    stateTags: ['distraido'],
    moodTags: ['distraido', 'focar'],
  },
  {
    id: 'deep-sleep-protocol',
    category: 'sleep',
    name: 'Protocolo Sono Profundo',
    objective: 'Criar uma rotina noturna completa.',
    description: 'Delta progressivo, chuva e ruído marrom para sono profundo.',
    duration: 20,
    icon: '🌌',
    featured: false,
    guided: true,
    premium: true,
    frequencyLabel: 'Delta 0.5Hz - 2Hz',
    soundLabel: 'Chuva + ruido marrom',
    metric: 'sleep',
    expectedImpact: 3,
    audioConfig: {
      binaural: { base: 160, beat: 0.8 },
      ambient: 'rain',
      ambientGain: 0.24,
      noise: 'brown',
      noiseGain: 0.18,
      binauralGain: 0.14,
    },
    tags: ['premium', 'sono profundo', 'delta'],
    stateTags: ['cansado'],
    moodTags: ['cansado', 'dormir'],
  },
  {
    id: 'anxiety-protocol',
    category: 'relax',
    name: 'Protocolo Ansiedade',
    objective: 'Atravessar momentos de tensão alta com suporte completo.',
    description: 'Theta, Alpha e 432Hz com mar para estabilização gradual.',
    duration: 12,
    icon: '🧘',
    featured: false,
    guided: true,
    premium: true,
    frequencyLabel: 'Theta + Alpha + 432Hz',
    soundLabel: 'Mar',
    metric: 'anxiety',
    expectedImpact: 3,
    audioConfig: {
      binaural: { base: 190, beat: 6 },
      secondaryBinaural: { base: 230, beat: 10 },
      tone: 432,
      toneGain: 0.06,
      ambient: 'ocean',
      ambientGain: 0.2,
      noise: 'pink',
      noiseGain: 0.08,
      binauralGain: 0.13,
      secondaryGain: 0.06,
    },
    tags: ['premium', 'ansiedade', 'theta'],
    stateTags: ['ansioso', 'pensando-demais'],
    moodTags: ['ansioso', 'calmar'],
  },
  {
    id: 'creative-flow-10',
    category: 'clarity',
    name: 'Flow criativo em 10 minutos',
    objective: 'Destravar pensamento sem ficar acelerado.',
    description: 'Alpha 10Hz com floresta para clareza e associação livre.',
    duration: 10,
    icon: '🌀',
    featured: false,
    guided: true,
    premium: true,
    frequencyLabel: 'Alpha 10Hz',
    soundLabel: 'Floresta',
    metric: 'clarity',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 200, beat: 10 },
      ambient: 'forest',
      ambientGain: 0.16,
      noise: 'pink',
      noiseGain: 0.08,
      binauralGain: 0.16,
    },
    tags: ['premium', 'criatividade', 'alpha'],
    stateTags: ['pensando-demais', 'distraido'],
    moodTags: ['pensando-demais', 'focar'],
  },
  {
    id: 'motivation-boost',
    category: 'energy',
    name: 'Protocolo Energia Alta',
    objective: 'Aumentar prontidão antes de treino, estudo ou trabalho.',
    description: 'Beta 25Hz com ruido branco controlado para ativacao intensa.',
    duration: 10,
    icon: '🔥',
    featured: false,
    guided: true,
    premium: true,
    frequencyLabel: 'Beta 25Hz',
    soundLabel: 'Ruido branco',
    metric: 'energy',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 220, beat: 25 },
      noise: 'white',
      noiseGain: 0.08,
      binauralGain: 0.2,
    },
    tags: ['premium', 'energia', 'beta'],
    stateTags: ['sem-energia'],
    moodTags: ['sem-energia', 'energia'],
  },
  {
    id: 'gamma-40hz',
    category: 'focus',
    name: 'Gamma 40Hz — Mente Clara',
    objective: 'Ativar cognição máxima e eliminar névoa mental.',
    description: '40Hz puro com ruído rosa suave — o estado de maior clareza e integração neural.',
    duration: 20,
    icon: '🧠',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: '40Hz Gamma',
    soundLabel: 'Ruído rosa',
    metric: 'focus',
    expectedImpact: 3,
    audioConfig: {
      binaural: { base: 200, beat: 40 },
      tone: 40,
      toneGain: 0.04,
      noise: 'pink',
      noiseGain: 0.07,
      binauralGain: 0.16,
    },
    tags: ['gamma', '40hz', 'foco', '20 min'],
    stateTags: ['distraido', 'pensando-demais'],
    moodTags: ['distraido', 'focar'],
  },
  {
    id: 'morning-rise',
    category: 'energy',
    name: 'Energia Matinal',
    objective: 'Ativar corpo e mente ao começar o dia.',
    description: 'Beta 18Hz com textura de ondas leves — substitui o café mental da manhã.',
    duration: 15,
    icon: '☀️',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Beta 18Hz',
    soundLabel: 'Ondas',
    metric: 'energy',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 230, beat: 18 },
      ambient: 'ocean',
      ambientGain: 0.14,
      noise: 'white',
      noiseGain: 0.05,
      binauralGain: 0.17,
    },
    tags: ['energia', 'beta', 'manhã', '15 min'],
    stateTags: ['sem-energia', 'cansado'],
    moodTags: ['sem-energia', 'energia'],
  },
  {
    id: 'theta-meditation',
    category: 'relax',
    name: 'Meditação Theta Profunda',
    objective: 'Entrar em estado meditativo sem esforço.',
    description: 'Theta 5Hz com floresta e chuva suave — o estado entre vigília e sonho.',
    duration: 20,
    icon: '🧘',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Theta 5Hz',
    soundLabel: 'Floresta + chuva',
    metric: 'anxiety',
    expectedImpact: 3,
    audioConfig: {
      binaural: { base: 190, beat: 5 },
      ambient: 'forest',
      ambientGain: 0.2,
      noise: 'brown',
      noiseGain: 0.12,
      binauralGain: 0.14,
    },
    tags: ['meditação', 'theta', 'floresta', '20 min'],
    stateTags: ['ansioso', 'pensando-demais'],
    moodTags: ['ansioso', 'calmar'],
  },
  // ── MEDITAÇÃO ──────────────────────────────────────────────────────────
  {
    id: 'meditation-528hz',
    category: 'meditation',
    name: '528Hz — Frequência da Cura',
    objective: 'Entrar em estado meditativo profundo com 528Hz.',
    description: 'Theta 5Hz + 528Hz com floresta — o tom da transformação e presença total.',
    duration: 20,
    icon: '🕉️',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Theta 5Hz + 528Hz',
    soundLabel: 'Floresta',
    metric: 'anxiety',
    expectedImpact: 3,
    audioConfig: {
      binaural: { base: 190, beat: 5 },
      tone: 528,
      toneGain: 0.06,
      ambient: 'forest',
      ambientGain: 0.18,
      noise: 'brown',
      noiseGain: 0.08,
      binauralGain: 0.13,
    },
    tags: ['meditação', 'theta', '528hz', 'floresta', '20 min'],
    stateTags: ['ansioso', 'pensando-demais'],
    moodTags: ['ansioso', 'calmar'],
  },
  {
    id: 'meditation-delta',
    category: 'meditation',
    name: 'Meditação Silenciosa',
    objective: 'Silêncio interior profundo sem esforço.',
    description: 'Delta 1Hz com chuva suave — o limiar entre vigília e sono.',
    duration: 30,
    icon: '🌧️',
    featured: false,
    guided: true,
    premium: false,
    frequencyLabel: 'Delta 1Hz',
    soundLabel: 'Chuva suave',
    metric: 'anxiety',
    expectedImpact: 3,
    audioConfig: {
      binaural: { base: 170, beat: 1 },
      ambient: 'rain',
      ambientGain: 0.22,
      noise: 'brown',
      noiseGain: 0.14,
      binauralGain: 0.12,
    },
    tags: ['meditação', 'delta', 'chuva', '30 min'],
    stateTags: ['ansioso', 'pensando-demais'],
    moodTags: ['calmar', 'ansioso'],
  },
  {
    id: 'meditation-432hz',
    category: 'meditation',
    name: 'Harmonia 432Hz',
    objective: 'Equilíbrio interno com o tom natural do universo.',
    description: 'Theta 6Hz + 432Hz com mar — ressonância que acalma o sistema nervoso.',
    duration: 15,
    icon: '🎵',
    featured: false,
    guided: true,
    premium: false,
    frequencyLabel: 'Theta 6Hz + 432Hz',
    soundLabel: 'Mar',
    metric: 'anxiety',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 195, beat: 6 },
      tone: 432,
      toneGain: 0.07,
      ambient: 'ocean',
      ambientGain: 0.18,
      noise: 'pink',
      noiseGain: 0.07,
      binauralGain: 0.13,
    },
    tags: ['meditação', '432hz', 'theta', 'mar', '15 min'],
    stateTags: ['ansioso'],
    moodTags: ['calmar', 'ansioso'],
  },

  // ── CRIATIVIDADE ───────────────────────────────────────────────────────
  {
    id: 'creative-alpha',
    category: 'creative',
    name: 'Flow Criativo Alpha',
    objective: 'Destravar a mente para criar sem bloqueios.',
    description: 'Alpha 10Hz com ondas — o estado de associação livre e inspiração.',
    duration: 20,
    icon: '🎨',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Alpha 10Hz',
    soundLabel: 'Ondas',
    metric: 'clarity',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 200, beat: 10 },
      ambient: 'ocean',
      ambientGain: 0.15,
      noise: 'pink',
      noiseGain: 0.08,
      binauralGain: 0.16,
    },
    tags: ['criatividade', 'alpha', 'ondas', '20 min'],
    stateTags: ['distraido', 'pensando-demais'],
    moodTags: ['focar', 'distraido'],
  },
  {
    id: 'creative-432-flow',
    category: 'creative',
    name: 'Inspiração 432Hz',
    objective: 'Conectar com intuição e pensamento lateral.',
    description: 'Alpha 8Hz + 432Hz com floresta — cria pontes entre hemisférios cerebrais.',
    duration: 25,
    icon: '🌀',
    featured: false,
    guided: true,
    premium: false,
    frequencyLabel: 'Alpha 8Hz + 432Hz',
    soundLabel: 'Floresta',
    metric: 'clarity',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 205, beat: 8 },
      tone: 432,
      toneGain: 0.05,
      ambient: 'forest',
      ambientGain: 0.17,
      noise: 'pink',
      noiseGain: 0.07,
      binauralGain: 0.14,
    },
    tags: ['criatividade', 'alpha', '432hz', 'floresta', '25 min'],
    stateTags: ['pensando-demais', 'distraido'],
    moodTags: ['focar', 'distraido'],
  },
  {
    id: 'creative-night',
    category: 'creative',
    name: 'Criação Noturna',
    objective: 'Aproveitar a calma da noite para criar.',
    description: 'Theta 7Hz suave com chuva — o estado hipnagógico favorece ideias únicas.',
    duration: 30,
    icon: '🌙',
    featured: false,
    guided: true,
    premium: true,
    frequencyLabel: 'Theta 7Hz',
    soundLabel: 'Chuva',
    metric: 'clarity',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 195, beat: 7 },
      ambient: 'rain',
      ambientGain: 0.2,
      noise: 'brown',
      noiseGain: 0.1,
      binauralGain: 0.14,
    },
    tags: ['criatividade', 'theta', 'chuva', 'noite', '30 min'],
    stateTags: ['pensando-demais'],
    moodTags: ['focar'],
  },

  // ── ALTA PERFORMANCE ───────────────────────────────────────────────────
  {
    id: 'performance-40hz',
    category: 'performance',
    name: 'Gamma 40Hz — Peak State',
    objective: 'Máxima cognição antes de uma entrega crítica.',
    description: '40Hz + Beta 25Hz com ruído branco — o estado de performance mental total.',
    duration: 15,
    icon: '🏆',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: '40Hz + Beta 25Hz',
    soundLabel: 'Ruído branco',
    metric: 'focus',
    expectedImpact: 3,
    audioConfig: {
      binaural: { base: 220, beat: 40 },
      secondaryBinaural: { base: 255, beat: 25 },
      noise: 'white',
      noiseGain: 0.06,
      binauralGain: 0.17,
      secondaryGain: 0.09,
    },
    tags: ['performance', 'gamma', '40hz', 'beta', '15 min'],
    stateTags: ['distraido', 'sem-energia'],
    moodTags: ['focar', 'energia'],
  },
  {
    id: 'performance-pre-treino',
    category: 'performance',
    name: 'Pré-Treino Mental',
    objective: 'Preparar mente e corpo para esforço intenso.',
    description: 'Beta 22Hz com ondas — ativa motivação e alerta sem ansiedade.',
    duration: 10,
    icon: '💪',
    featured: false,
    guided: true,
    premium: false,
    frequencyLabel: 'Beta 22Hz',
    soundLabel: 'Ondas',
    metric: 'energy',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 230, beat: 22 },
      ambient: 'ocean',
      ambientGain: 0.12,
      noise: 'white',
      noiseGain: 0.06,
      binauralGain: 0.19,
    },
    tags: ['performance', 'beta', 'ondas', 'treino', '10 min'],
    stateTags: ['sem-energia'],
    moodTags: ['energia', 'focar'],
  },
  {
    id: 'performance-recovery',
    category: 'performance',
    name: 'Recuperação Ativa',
    objective: 'Restaurar após esforço intenso sem dormir.',
    description: 'Alpha 9Hz com floresta — recarrega sem deixar sonolento.',
    duration: 20,
    icon: '🔄',
    featured: false,
    guided: true,
    premium: true,
    frequencyLabel: 'Alpha 9Hz',
    soundLabel: 'Floresta',
    metric: 'energy',
    expectedImpact: 2,
    audioConfig: {
      binaural: { base: 210, beat: 9 },
      ambient: 'forest',
      ambientGain: 0.18,
      noise: 'pink',
      noiseGain: 0.09,
      binauralGain: 0.14,
    },
    tags: ['performance', 'alpha', 'recuperação', 'floresta', '20 min'],
    stateTags: ['cansado', 'sem-energia'],
    moodTags: ['energia'],
  },

  {
    id: 'sleep-432hz',
    category: 'sleep',
    name: '432Hz Noturno',
    objective: 'Adormecer em harmonia com sons naturais.',
    description: '432Hz com Delta 1Hz e ruído marrom profundo para soltar tensões do dia.',
    duration: 30,
    icon: '🌌',
    featured: true,
    guided: true,
    premium: false,
    frequencyLabel: 'Delta 1Hz + 432Hz',
    soundLabel: 'Ruído marrom',
    metric: 'sleep',
    expectedImpact: 3,
    audioConfig: {
      binaural: { base: 175, beat: 1 },
      tone: 432,
      toneGain: 0.05,
      noise: 'brown',
      noiseGain: 0.2,
      binauralGain: 0.12,
    },
    tags: ['sono', 'delta', '432hz', 'marrom', '30 min'],
    stateTags: ['cansado'],
    moodTags: ['cansado', 'dormir'],
  },
];

const MOOD_MAP = {
  ansioso: ['anxiety-now', 'mental-reset-3', 'theta-meditation', 'calm-10', 'anxiety-protocol'],
  cansado: ['sleep-15', 'sleep-432hz', 'micro-nap-10', 'energy-now', 'deep-sleep-protocol'],
  distraido: ['focus-5', 'gamma-40hz', 'performance-10', 'mental-reset-3', 'creative-flow-10'],
  'sem-energia': ['morning-rise', 'energy-now', 'focus-5', 'motivation-boost', 'micro-nap-10'],
  'pensando-demais': ['mental-reset-3', 'gamma-40hz', 'anxiety-now', 'theta-meditation', 'creative-flow-10'],

  // Legacy aliases kept for existing localStorage users.
  calmar: ['anxiety-now', 'theta-meditation', 'meditation-528hz', 'calm-10', 'mental-reset-3'],
  dormir: ['sleep-15', 'sleep-432hz', 'micro-nap-10', 'deep-sleep-protocol'],
  focar: ['focus-5', 'gamma-40hz', 'performance-40hz', 'creative-alpha', 'performance-10'],
  ansiedade: ['anxiety-now', 'meditation-528hz', 'theta-meditation', 'mental-reset-3'],
  energia: ['morning-rise', 'energy-now', 'performance-40hz', 'motivation-boost'],
  meditacao: ['meditation-528hz', 'theta-meditation', 'meditation-432hz', 'meditation-delta'],
  criatividade: ['creative-alpha', 'creative-432-flow', 'creative-flow-10', 'creative-night'],
  performance: ['performance-40hz', 'performance-pre-treino', 'gamma-40hz', 'performance-recovery'],
};
