export const S = {
  pillar:          "/aldeia-das-aguas/",
  preco:           "/aldeia-das-aguas-preco/",
  ingresso:        "/ingresso-aldeia-das-aguas/",
  desconto:        "/aldeia-das-aguas-desconto/",
  dayUse:          "/day-use-aldeia-das-aguas/",
  pacote:          "/pacote-aldeia-das-aguas/",
  hotel:           "/hotel-aldeia-das-aguas/",
  ondeFicar:       "/onde-ficar-perto-da-aldeia-das-aguas/",
  airbnb:          "/airbnb-aldeia-das-aguas/",
  ondeFica:        "/aldeia-das-aguas-onde-fica/",
  comoChegar:      "/como-chegar-na-aldeia-das-aguas/",
  endereco:        "/aldeia-das-aguas-endereco/",
  telefone:        "/aldeia-das-aguas-telefone/",
  atracoes:        "/atracoes-da-aldeia-das-aguas/",
  horario:         "/aldeia-das-aguas-horario-de-funcionamento/",
  kilimanjaro:     "/kilimanjaro-aldeia-das-aguas/",
  valeAPena:       "/aldeia-das-aguas-vale-a-pena/",
  dicas:           "/dicas-aldeia-das-aguas/",
  melhorDia:       "/melhor-dia-aldeia-das-aguas/",
  familia:         "/aldeia-das-aguas-com-criancas/",
  opiniao:         "/aldeia-das-aguas-opiniao/",
  parquesRj:       "/parques-aquaticos-rj/",
  melhoresBrasil:  "/melhores-parques-aquaticos-brasil/",
  barraDoIrai:     "/o-que-fazer-barra-do-pirai/",
  parquesSp:       "/parques-aquaticos-sp/",
  parquesSc:       "/parques-aquaticos-sc/",
  parquesNordeste: "/parques-aquaticos-nordeste/",
  // Hub pages (grupos)
  hubCompra:       "/aldeia-das-aguas-compra/",
  hubHospedagem:   "/aldeia-das-aguas-hospedagem/",
  hubPlanejamento: "/aldeia-das-aguas-planejamento/",
} as const;
