import type { SiloPageDefinition } from "../../types.js";

export const INFORMATIONAL_CHILD_PAGES: SiloPageDefinition[] = [
  {
    key: "onde-fica",
    title: "Aldeia das Aguas Onde Fica",
    slug: "aldeia-das-aguas-onde-fica",
    keyword: "aldeia das aguas onde fica",
    type: "informational",
    schemaType: "Article",
    siblings: ["como-chegar", "endereco", "telefone"],
    commercialTargets: ["ingresso", "preco"],
  },
  {
    key: "como-chegar",
    title: "Como Chegar na Aldeia das Aguas",
    slug: "como-chegar-aldeia-das-aguas",
    keyword: "como chegar na aldeia das aguas",
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "endereco", "horario"],
    commercialTargets: ["preco", "ingresso"],
  },
  {
    key: "endereco",
    title: "Aldeia das Aguas Endereco",
    slug: "aldeia-das-aguas-endereco",
    keyword: "aldeia das aguas endereco",
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "como-chegar", "telefone"],
    commercialTargets: ["ingresso", "preco"],
  },
  {
    key: "telefone",
    title: "Aldeia das Aguas Telefone",
    slug: "aldeia-das-aguas-telefone",
    keyword: "aldeia das aguas telefone",
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "endereco"],
    commercialTargets: ["ingresso", "pacote"],
  },
  {
    key: "atracoes",
    title: "Atracoes da Aldeia das Aguas",
    slug: "atracoes-aldeia-das-aguas",
    keyword: "atracoes da aldeia das aguas",
    secondaryKeywords: ["o que tem na aldeia das aguas", "atrações aldeia das aguas"],
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "dicas", "familia"],
    commercialTargets: ["ingresso", "preco", "pacote"],
  },
  {
    key: "horario",
    title: "Aldeia das Aguas Horario de Funcionamento",
    slug: "aldeia-das-aguas-horario",
    keyword: "aldeia das aguas horario de funcionamento",
    secondaryKeywords: ["aldeia das aguas horario", "horario aldeia das aguas park resort"],
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "como-chegar", "melhor-dia"],
    commercialTargets: ["ingresso", "preco"],
  },
];
