import type { SiloPageDefinition } from "../../types.js";

export const SEO_CHILD_PAGES: SiloPageDefinition[] = [
  {
    key: "vale-a-pena",
    title: "Aldeia das \u00c1guas Vale a Pena?",
    slug: "aldeia-das-aguas-vale-a-pena",
    keyword: "aldeia das aguas vale a pena",
    type: "seo",
    schemaType: "FAQ",
    siblings: ["dicas", "melhor-dia", "opiniao"],
    commercialTargets: ["ingresso", "preco", "desconto"],
  },
  {
    key: "dicas",
    title: "Dicas para a Aldeia das \u00c1guas",
    slug: "dicas-aldeia-das-aguas",
    keyword: "dicas aldeia das aguas",
    type: "seo",
    schemaType: "Article",
    siblings: ["vale-a-pena", "melhor-dia", "atracoes"],
    commercialTargets: ["ingresso", "preco"],
  },
  {
    key: "melhor-dia",
    title: "Melhor Dia para Ir \u00e0 Aldeia das \u00c1guas",
    slug: "melhor-dia-aldeia-das-aguas",
    keyword: "melhor dia para ir aldeia das aguas",
    type: "seo",
    schemaType: "Article",
    siblings: ["dicas", "vale-a-pena", "horario"],
    commercialTargets: ["ingresso", "desconto"],
  },
  {
    key: "familia",
    title: "Aldeia das \u00c1guas com Crian\u00e7as",
    slug: "aldeia-das-aguas-com-criancas",
    keyword: "aldeia das aguas com criancas",
    secondaryKeywords: ["aldeia das aguas criancas", "aldeia das aguas familia"],
    type: "seo",
    schemaType: "FAQ",
    siblings: ["dicas", "vale-a-pena", "atracoes"],
    commercialTargets: ["ingresso", "preco", "pacote"],
  },
  {
    key: "opiniao",
    title: "Opini\u00e3o sobre a Aldeia das \u00c1guas",
    slug: "aldeia-das-aguas-opiniao",
    keyword: "aldeia das aguas opiniao",
    secondaryKeywords: ["aldeia das aguas review", "aldeia das aguas avaliacao"],
    type: "seo",
    schemaType: "FAQ",
    siblings: ["vale-a-pena", "dicas", "familia"],
    commercialTargets: ["ingresso", "preco"],
  },
];
