import type { SiloPageDefinition } from "../../types.js";

export const INFORMATIONAL_CHILD_PAGES: SiloPageDefinition[] = [
  {
    key: "onde-fica",
    title: "Onde Fica a Aldeia das \u00c1guas",
    slug: "aldeia-das-aguas-onde-fica",
    keyword: "aldeia das aguas onde fica",
    type: "informational",
    schemaType: "Article",
    siblings: ["como-chegar", "endereco", "telefone"],
    commercialTargets: ["ingresso", "preco"],
  },
  {
    key: "como-chegar",
    title: "Como Chegar na Aldeia das \u00c1guas",
    slug: "como-chegar-aldeia-das-aguas",
    keyword: "como chegar na aldeia das aguas",
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "endereco", "horario"],
    commercialTargets: ["preco", "ingresso"],
  },
  {
    key: "endereco",
    title: "Endere\u00e7o da Aldeia das \u00c1guas",
    slug: "aldeia-das-aguas-endereco",
    keyword: "aldeia das aguas endereco",
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "como-chegar", "telefone"],
    commercialTargets: ["ingresso", "preco"],
  },
  {
    key: "telefone",
    title: "Telefone da Aldeia das \u00c1guas",
    slug: "aldeia-das-aguas-telefone",
    keyword: "aldeia das aguas telefone",
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "endereco"],
    commercialTargets: ["ingresso", "pacote"],
  },
  {
    key: "atracoes",
    title: "Atra\u00e7\u00f5es da Aldeia das \u00c1guas",
    slug: "atracoes-aldeia-das-aguas",
    keyword: "atracoes da aldeia das aguas",
    secondaryKeywords: ["o que tem na aldeia das aguas", "atracoes aldeia das aguas"],
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "dicas", "familia"],
    commercialTargets: ["ingresso", "preco", "pacote"],
  },
  {
    key: "horario",
    title: "Hor\u00e1rio da Aldeia das \u00c1guas",
    slug: "aldeia-das-aguas-horario",
    keyword: "aldeia das aguas horario de funcionamento",
    secondaryKeywords: ["aldeia das aguas horario", "horario aldeia das aguas park resort"],
    type: "informational",
    schemaType: "Article",
    siblings: ["onde-fica", "como-chegar", "melhor-dia"],
    commercialTargets: ["ingresso", "preco"],
  },
  {
    key: "kilimanjaro",
    title: "Kilimanjaro da Aldeia das \u00c1guas",
    slug: "kilimanjaro-aldeia-das-aguas",
    keyword: "kilimanjaro aldeia das aguas",
    secondaryKeywords: ["toboga mais alto do mundo", "toboga radical aldeia das aguas"],
    type: "informational",
    schemaType: "Article",
    siblings: ["atracoes", "dicas", "vale-a-pena"],
    commercialTargets: ["ingresso", "preco"],
  },
];
