import type { SiloPageDefinition } from "../../types.js";

export const COMMERCIAL_CHILD_PAGES: SiloPageDefinition[] = [
  {
    key: "preco",
    title: "Pre\u00e7o da Aldeia das \u00c1guas",
    slug: "aldeia-das-aguas-preco",
    keyword: "aldeia das aguas preco",
    type: "commercial",
    schemaType: "FAQ",
    siblings: ["ingresso", "desconto", "pacote"],
    commercialTargets: ["ingresso", "desconto", "pacote"],
  },
  {
    key: "ingresso",
    title: "Ingresso da Aldeia das \u00c1guas",
    slug: "ingresso-aldeia-das-aguas",
    keyword: "ingresso aldeia das aguas",
    type: "commercial",
    schemaType: "FAQ",
    siblings: ["preco", "desconto", "day-use"],
    commercialTargets: ["preco", "desconto", "pacote"],
  },
  {
    key: "desconto",
    title: "Desconto na Aldeia das \u00c1guas",
    slug: "aldeia-das-aguas-desconto",
    keyword: "aldeia das aguas desconto",
    type: "commercial",
    schemaType: "FAQ",
    siblings: ["preco", "ingresso", "pacote"],
    commercialTargets: ["preco", "ingresso", "pacote"],
  },
  {
    key: "day-use",
    title: "Day Use da Aldeia das \u00c1guas",
    slug: "day-use-aldeia-das-aguas",
    keyword: "day use aldeia das aguas",
    type: "commercial",
    schemaType: "FAQ",
    siblings: ["preco", "ingresso", "pacote"],
    commercialTargets: ["preco", "ingresso", "pacote"],
  },
  {
    key: "pacote",
    title: "Pacote da Aldeia das \u00c1guas",
    slug: "pacote-aldeia-das-aguas",
    keyword: "pacote aldeia das aguas",
    type: "commercial",
    schemaType: "FAQ",
    siblings: ["preco", "ingresso", "desconto"],
    commercialTargets: ["preco", "ingresso", "desconto"],
  },
];
