import type { SiloPageDefinition } from "../../types.js";

export const TOP_FUNNEL_PAGES: SiloPageDefinition[] = [
  {
    key: "parques-aquaticos-rj",
    title: "Parques Aquaticos RJ",
    slug: "parques-aquaticos-rj",
    keyword: "parques aquaticos RJ",
    type: "top-funnel",
    schemaType: "Article",
    siblings: ["melhores-parques-aquaticos-brasil", "o-que-fazer-barra-do-pirai", "parques-aquaticos-sp"],
    commercialTargets: ["aldeia-das-aguas"],
  },
  {
    key: "melhores-parques-aquaticos-brasil",
    title: "Melhores Parques Aquaticos do Brasil",
    slug: "melhores-parques-aquaticos-brasil",
    keyword: "melhores parques aquaticos do Brasil",
    type: "top-funnel",
    schemaType: "Article",
    siblings: ["parques-aquaticos-rj", "parques-aquaticos-sp", "parques-aquaticos-nordeste"],
    commercialTargets: ["aldeia-das-aguas"],
  },
  {
    key: "o-que-fazer-barra-do-pirai",
    title: "O Que Fazer em Barra do Pirai",
    slug: "o-que-fazer-barra-do-pirai",
    keyword: "o que fazer em Barra do Pirai",
    type: "top-funnel",
    schemaType: "Article",
    siblings: ["parques-aquaticos-rj", "melhores-parques-aquaticos-brasil"],
    commercialTargets: ["aldeia-das-aguas"],
  },
  {
    key: "parques-aquaticos-sp",
    title: "Parques Aquaticos SP",
    slug: "parques-aquaticos-sp",
    keyword: "parques aquaticos SP",
    secondaryKeywords: ["parques aquaticos Sao Paulo", "melhor parque aquatico SP"],
    type: "top-funnel",
    schemaType: "Article",
    siblings: ["parques-aquaticos-rj", "melhores-parques-aquaticos-brasil", "parques-aquaticos-sc"],
    commercialTargets: ["aldeia-das-aguas"],
  },
  {
    key: "parques-aquaticos-sc",
    title: "Parques Aquaticos Santa Catarina",
    slug: "parques-aquaticos-sc",
    keyword: "parques aquaticos Santa Catarina",
    secondaryKeywords: ["parques aquaticos SC", "melhor parque aquatico Santa Catarina"],
    type: "top-funnel",
    schemaType: "Article",
    siblings: ["parques-aquaticos-rj", "melhores-parques-aquaticos-brasil", "parques-aquaticos-sp"],
    commercialTargets: ["aldeia-das-aguas"],
  },
  {
    key: "parques-aquaticos-nordeste",
    title: "Parques Aquaticos Nordeste",
    slug: "parques-aquaticos-nordeste",
    keyword: "parques aquaticos nordeste",
    secondaryKeywords: ["parques aquaticos Fortaleza", "parques aquaticos Recife"],
    type: "top-funnel",
    schemaType: "Article",
    siblings: ["parques-aquaticos-rj", "melhores-parques-aquaticos-brasil", "parques-aquaticos-sc"],
    commercialTargets: ["aldeia-das-aguas"],
  },
];
